// Generated by CoffeeScript 1.6.1
(function() {
  var sentenceSimilarity;

  sentenceSimilarity = function(stemA, stemB) {
    return _.intersection(stemA, stemB).length;
  };

  this.answer = (function() {

    function answer() {
      this.tag = new POSTagger().tag;
      this.tokenize = new Lexer().lex;
      this.stem = natural.PorterStemmer.tokenizeAndStem;
      this.sentences = [];
      this.stemmedSentences = [];
    }

    answer.prototype.read = function(article) {
      var sentences, stem, stemmed;
      stem = this.stem;
      sentences = this.sentences.concat(article.split("."));
      stemmed = _.map(sentences, function(text) {
        return stem(text);
      });
      this.sentences = this.sentences.concat(sentences);
      return this.stemmedSentences = this.stemmedSentences.concat(stemmed);
    };

    answer.prototype.match = function(sentence) {
      var corpus, scores, stemA, stemmedCorpus;
      corpus = this.sentences;
      stemmedCorpus = this.stemmedSentences;
      stemA = this.stem(sentence);
      scores = _.map(stemmedCorpus, function(stemB) {
        return sentenceSimilarity(stemA, stemB);
      });
      return _.sortBy(_.zip(scores, corpus), function(x) {
        return -1 * x[0];
      });
    };

    return answer;

  })();

}).call(this);
